# Generated by Django 4.1.7 on 2023-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("description", models.TextField()),
                (
                    "for_gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(height_field=100, upload_to="", width_field=100),
                ),
                (
                    "for_age",
                    models.CharField(
                        choices=[
                            ("Under 18", "Under 18"),
                            ("18-25", "Between 18 25"),
                            ("26-35", "Between 26 35"),
                            ("36-45", "Between 36 45"),
                            ("46-55", "Between 46 55"),
                            ("56-65", "Between 56 65"),
                            ("Over 65", "Over 65"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
