# Generated by Django 4.1.7 on 2023-04-05 07:09

from django.db import migrations, models
import gift.models


class Migration(migrations.Migration):
    dependencies = [
        ("gift", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gift",
            name="for_age",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="for_gender",
        ),
        migrations.AddField(
            model_name="gift",
            name="age",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Under 18", "Under 18"),
                    ("18-25", "Between 18 25"),
                    ("26-35", "Between 26 35"),
                    ("36-45", "Between 36 45"),
                    ("46-55", "Between 46 55"),
                    ("56-65", "Between 56 65"),
                    ("Over 65", "Over 65"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Both", "Both"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="likes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Computer", "Computer"),
                    ("Dance", "Dance"),
                    ("Football", "Football"),
                    ("Basketball", "Basketball"),
                    ("Gadget", "Gadget"),
                    ("Clothes", "Clothes"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="occasion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Birthday", "Birthday"),
                    ("Wedding", "Wedding"),
                    ("New year", "New Year"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="gift",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=gift.models.gift_image_file_path,
            ),
        ),
    ]
