# Generated by Django 4.1.7 on 2023-04-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gift", "0002_remove_gift_for_age_remove_gift_for_gender_gift_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="likes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Computer", "Computer"),
                    ("Dance", "Dance"),
                    ("Sport", "Sport"),
                    ("Gadget", "Gadget"),
                    ("Clothes", "Clothes"),
                ],
                max_length=15,
            ),
        ),
    ]
