# Generated by Django 4.1.7 on 2023-04-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gift", "0003_alter_gift_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="age",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-16", "Under 18"),
                    ("17-25", "Between 18 25"),
                    ("26-45", "Between 26 35"),
                    ("46-100", "Over 45"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gift",
            name="likes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IT", "It"),
                    ("Beauty", "Beauty"),
                    ("Sport", "Sport"),
                    ("Cars", "Cars"),
                    ("Fashion", "Fashion"),
                    ("Music", "Music"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="gift",
            name="occasion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Birthday", "Birthday"),
                    ("Wedding", "Wedding"),
                    ("New Year", "New Year"),
                    ("Valentines Day", "Valentines Day"),
                    ("Graduation", "Graduation"),
                ],
                max_length=15,
            ),
        ),
    ]
