# Generated by Django 4.1.7 on 2023-04-10 08:06

from django.db import migrations
from django.core.management import call_command


def func(apps, schema_editor):
    call_command("loaddata", "data_fixture.json")


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [migrations.RunPython(func)]
